forge "http://forge.puppetlabs.com"

mod 'puppetlabs/apt'
mod 'stankevich/python'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/nodejs'
mod 'puppetlabs/mongodb'
mod 'puppetlabs/postgresql'
mod 'camptocamp/postgis'

# mod 'puppetlabs/stdlib'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'
