su - vagrant -c     "sh $V_S/ke_10_clone_code.sh"
su - root -c        "sh $V_S/ke_20_apt_installs.sh"
su - root -c        "sh $V_S/ke_30_start_redis.sh"
su - vagrant -c     "sh $V_S/ke_40_npm_installs.sh"
su - vagrant -c     "sh $V_S/ke_50_build_statics.sh"
su - root -c        "sh $V_S/ke_60_start_pm2.sh"
